# layers are as presented in bazecor (the layer number) minus 1
# layer to return to when no matching window is found
base_layer: 0
# layers matched with their corresponding programs (or exe-files)
layers:
  3:
    - GenshinImpact.exe
    - eso.exe
    - bg3.exe
    - bg3_dx11.exe
  4:
    - blender

# interval in which the active window is checked in seconds
refresh_interval: 1
# port of the keyboard for RF and USB, can be seen when selecting the keyboard in bazecor
PORT: COM5
# bazecor exe name
bazecor: Bazecor.exe
## change modes between: rf, wired, bluetooth, bl, automatic
mode: rf
#bluetooth_address: "da:2e:bf:9f:4d:00"